name: docx-processor
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip>=21.0
  # Runtime dependencies
  - mammoth>=1.5.0 # Word document parsing and HTML conversion
  - beautifulsoup4>=4.11.0 # HTML parsing and manipulation
  - pillow>=9.0.0 # Image processing and optimization
  - lxml>=4.9.0 # XML/HTML processing backend (faster parsing)
  # Development dependencies
  - pytest>=7.0.0 # Testing
  - black>=22.0.0 # Code formatting
  - pylint>=2.12.0 # Linting
  - mypy>=0.950 # Type checking
  - jupyter # For development notebooks
  # Build tools
  - build # Building packages
  - setuptools>=64.0.0 # Build backend
  - wheel # Build wheel packages
  - pip:
      - python-mammoth>=1.5.0 # Official name on PyPI is python-mammoth
